version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: usermanager-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: usermanager
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb/init:/docker-entrypoint-initdb.d
    networks:
      - usermanager-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL Database for Keycloak
  postgres:
    image: postgres:15-alpine
    container_name: usermanager-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - usermanager-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    container_name: usermanager-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_STRICT: false
      KC_LOG_LEVEL: INFO
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - usermanager-network
    restart: unless-stopped
    command: start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # User Manager Application
  user-manager-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: usermanager-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MONGODB_URI: mongodb://admin:password@mongodb:27017/usermanager?authSource=admin
      MONGODB_DATABASE: usermanager
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080
      KEYCLOAK_ISSUER_URI: http://localhost:8080/realms/usermanager
      KEYCLOAK_JWK_SET_URI: http://keycloak:8080/realms/usermanager/protocol/openid-connect/certs
      KEYCLOAK_REALM: usermanager
      KEYCLOAK_CLIENT_ID: user-manager-client
      KEYCLOAK_CLIENT_SECRET: your-client-secret
      SERVER_PORT: 8081
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:4200
    ports:
      - "8081:8081"
    depends_on:
      mongodb:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - usermanager-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/api/v1/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # MongoDB Express (Database Admin Tool)
  mongo-express:
    image: mongo-express:latest
    container_name: usermanager-mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8082:8081"
    depends_on:
      - mongodb
    networks:
      - usermanager-network
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local
  postgres_data:
    driver: local
  keycloak_data:
    driver: local

networks:
  usermanager-network:
    driver: bridge