spring:
  application:
    name: user-manager-microservice
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/usermanager}
      database: ${MONGODB_DATABASE:usermanager}
      auto-index-creation: true
      
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/usermanager}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/usermanager/protocol/openid-connect/certs}

  cache:
    type: simple

# Keycloak Configuration
keycloak:
  realm: ${KEYCLOAK_REALM:usermanager}
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080}
  resource: ${KEYCLOAK_CLIENT_ID:user-manager-client}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:your-client-secret}
  use-resource-role-mappings: true
  bearer-only: true

# Server Configuration
server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /api/v1
  error:
    include-message: always
    include-binding-errors: always

# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Logging Configuration
logging:
  level:
    com.usermanager: ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:INFO}
    org.springframework.data.mongodb: ${MONGODB_LOG_LEVEL:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application Specific Configuration
app:
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:4200}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
    jwt:
      access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY:3600} # 1 hour
      refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY:86400} # 24 hours
  
  pagination:
    default-page-size: ${DEFAULT_PAGE_SIZE:20}
    max-page-size: ${MAX_PAGE_SIZE:100}

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/usermanager_dev

logging:
  level:
    com.usermanager: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.mongodb: DEBUG

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: WARN
    com.usermanager: INFO
    org.springframework.data.mongodb: WARN