spring:
  config:
    activate:
      on-profile: docker
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:usermanager}
    username: ${DB_USERNAME:usermanager}
    password: ${DB_PASSWORD:password}
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/usermanager}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/usermanager/protocol/openid-connect/certs}

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://keycloak:8080}
  issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/usermanager}

server:
  port: ${SERVER_PORT:8081}

logging:
  level:
    com.usermanager: INFO
    org.springframework.security: INFO